# Generated by Django 4.2.30 on 2026-05-26 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_principal', models.BooleanField(default=False, help_text='¿Es la bodega central?')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(help_text='Ej: FER, ELE, PVC', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Stock Total (Suma de bodegas)', max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral para alertas', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.categoria')),
            ],
            options={
                'verbose_name_plural': 'Inventario (Materiales y Consumibles)',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('centro_costos', models.CharField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para borrado lógico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega_proyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto_asociado', to='web.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación Admin'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PARCIALMENTE_DESPACHADO', 'Parcialmente Despachado'), ('DESPACHADO', 'Despachado Totalmente'), ('EN_COMPRAS', 'Enviado a Compras')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.proyecto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=10, unique=True)),
                ('ultimo_valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADO_A_COMPRAS', 'Pendiente de Cotización (En Compras)'), ('COTIZADO', 'Cotizado (Esperando Aprobación Admin)'), ('PROCESADO', 'Procesado (Órdenes Generadas / Rechazados)')], default='ENVIADO_A_COMPRAS', max_length=30)),
                ('observaciones_admin', models.TextField(blank=True)),
                ('requerimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('proveedor', models.CharField(help_text='Nombre de la ferretería o distribuidor', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Cotizando)'), ('EMITIDA', 'Emitida al Proveedor'), ('EN_TRANSITO', 'En tránsito (Logística)'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente (Alerta Compras)'), ('RECIBIDA', 'Recibida Total (Stock Actualizado)'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=25)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('documento_respaldo', models.FileField(blank=True, help_text='Factura o Certificado provisto por el proveedor', null=True, upload_to='compras_facturas/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso por Compra (Abastecimiento)'), ('SALIDA', 'Salida por Requerimiento (Despacho)'), ('AJUSTE', 'Ajuste Manual de Inventario'), ('VENTA', 'Venta a Terceros'), ('TRANSFERENCIA', 'Transferencia entre Bodegas')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('certificado_calidad', models.FileField(blank=True, help_text='Certificado de calidad subido por bodega', null=True, upload_to='certificados/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_ingreso', to='web.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='web.bodega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='web.material')),
                ('orden_compra_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.ordencompra')),
                ('requerimiento_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.requerimiento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRequerimiento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, editable=False, max_length=20)),
                ('fecha_solicitud', models.DateTimeField(blank=True, editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación Admin'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PARCIALMENTE_DESPACHADO', 'Parcialmente Despachado'), ('DESPACHADO', 'Despachado Totalmente'), ('EN_COMPRAS', 'Enviado a Compras')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.proyecto')),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical requerimiento',
                'verbose_name_plural': 'historical requerimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('centro_costos', models.CharField(blank=True, db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para borrado lógico')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bodega_proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.bodega')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto',
                'verbose_name_plural': 'historical proyectos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrdenCompra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, editable=False, max_length=20)),
                ('proveedor', models.CharField(help_text='Nombre de la ferretería o distribuidor', max_length=200)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Cotizando)'), ('EMITIDA', 'Emitida al Proveedor'), ('EN_TRANSITO', 'En tránsito (Logística)'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente (Alerta Compras)'), ('RECIBIDA', 'Recibida Total (Stock Actualizado)'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=25)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('documento_respaldo', models.TextField(blank=True, help_text='Factura o Certificado provisto por el proveedor', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical orden compra',
                'verbose_name_plural': 'historical Órdenes de Compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovimientoInventario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso por Compra (Abastecimiento)'), ('SALIDA', 'Salida por Requerimiento (Despacho)'), ('AJUSTE', 'Ajuste Manual de Inventario'), ('VENTA', 'Venta a Terceros'), ('TRANSFERENCIA', 'Transferencia entre Bodegas')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('certificado_calidad', models.TextField(blank=True, help_text='Certificado de calidad subido por bodega', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bodega_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.bodega')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.material')),
                ('orden_compra_asociada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.ordencompra')),
                ('requerimiento_asociado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.requerimiento')),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical movimiento inventario',
                'verbose_name_plural': 'historical movimiento inventarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Stock Total (Suma de bodegas)', max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral para alertas', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical material',
                'verbose_name_plural': 'historical Inventario (Materiales y Consumibles)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_item', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO_BODEGA', 'Aprobado para Despacho (Bodega)'), ('EN_COMPRAS', 'Mandar a Compras (Falta Stock)'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=30)),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.material')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.material')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor_cotizado', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=0, help_text='Días hábiles para entrega')),
                ('especificaciones_tecnicas', models.TextField(blank=True)),
                ('certificado_calidad_incluido', models.BooleanField(default=False)),
                ('archivo_cotizacion', models.FileField(blank=True, null=True, upload_to='cotizaciones/%Y/%m/%d/')),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado para Compra'), ('COMPRADO', 'Órden de Compra Generada'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.material')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cotizados', to='web.solicitudcompra')),
            ],
        ),
        migrations.CreateModel(
            name='StockBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='web.bodega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_bodegas', to='web.material')),
            ],
            options={
                'unique_together': {('material', 'bodega')},
            },
        ),
    ]
