# Generated by Django 4.2.30 on 2026-06-03 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterial',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='material',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
