# Generated by Django 4.2.30 on 2026-06-04 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_historicalmaterial_impuesto_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Inventario (Materiales y Consumibles)'},
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de impuesto (IVA, etc)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar para borrado lógico (mantiene histórico)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='nombre',
            field=models.CharField(help_text='Nombre comercial o norma técnica', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio unitario sin impuesto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='sku',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Código único auto-generado', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Stock Total (Suma de bodegas). Denormalizado para reportes rápidos.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral para alertas de reabastecimiento', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de impuesto (IVA, etc)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar para borrado lógico (mantiene histórico)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(help_text='Nombre comercial o norma técnica', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio unitario sin impuesto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, editable=False, help_text='Código único auto-generado', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Stock Total (Suma de bodegas). Denormalizado para reportes rápidos.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral para alertas de reabastecimiento', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['sku'], name='web_materia_sku_78c4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['categoria', 'is_active'], name='web_materia_categor_da1da6_idx'),
        ),
    ]
