# Generated by Django 4.2.30 on 2026-06-05 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega_asignada', models.ForeignKey(blank=True, help_text='Bodega sobre la cual el usuario tiene control logístico.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.bodega')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
