# Generated by Django 4.2.30 on 2026-06-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_bodega_is_principal_perfilempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='bodega_destino',
            field=models.ForeignKey(help_text='Bodega donde se necesita el material', null=True, on_delete=django.db.models.deletion.PROTECT, to='web.bodega'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('ENVIADO_A_COMPRAS', 'Pendiente de Cotización (En Compras)'), ('COTIZADO', 'Cotizado (Esperando Aprobación Admin)'), ('REVISADO_ADMIN', 'Revisado por Admin (Requiere Acción Compras)'), ('PROCESADO', 'Procesado (Órdenes Generadas)')], default='ENVIADO_A_COMPRAS', max_length=30),
        ),
    ]
