# Generated by Django 4.2.30 on 2026-06-11 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_detallerequerimiento_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionitem',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.bodega'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.bodega'),
        ),
    ]
