# Generated by Django 6.0.1 on 2026-09-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_cotizacionitem_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='cotizacion_item_origen',
            field=models.ForeignKey(blank=True, help_text='Línea de cotización de la que nació esta línea de Orden de Compra (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_orden', to='web.cotizacionitem'),
        ),
    ]
