# Generated by Django 6.0.1 on 2026-09-15 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_detalleordencompra_cotizacion_item_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequerimiento',
            name='estado_item',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO_BODEGA', 'Aprobado para Despacho (Bodega)'), ('EN_COMPRAS', 'Mandar a Compras (Falta Stock)'), ('DESPACHADO', 'Despachado Totalmente'), ('CERRADO_INCOMPLETO', 'Cerrado Incompleto por Bodega'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalrequerimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación Admin'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PARCIALMENTE_DESPACHADO', 'Parcialmente Despachado'), ('DESPACHADO', 'Despachado Totalmente'), ('EN_COMPRAS', 'Enviado a Compras'), ('CERRADO_INCOMPLETO', 'Cerrado Incompleto por Bodega')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación Admin'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PARCIALMENTE_DESPACHADO', 'Parcialmente Despachado'), ('DESPACHADO', 'Despachado Totalmente'), ('EN_COMPRAS', 'Enviado a Compras'), ('CERRADO_INCOMPLETO', 'Cerrado Incompleto por Bodega')], default='PENDIENTE', max_length=30),
        ),
        migrations.CreateModel(
            name='CierreIncompletoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('justificativo', models.TextField()),
                ('cantidad_solicitada_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_despachada_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_pendiente_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requerimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_incompleto', to='web.requerimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_incompletos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
