# Generated by Django 6.0.2 on 2026-05-14 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_solicitudcompra_cotizacionitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bodega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "is_principal",
                    models.BooleanField(
                        default=False, help_text="¿Es la bodega central?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria_padre",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material Estructural / Acero"),
                            ("CONSUMIBLE", "Consumible / Herramienta Menor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="movimientoinventario",
            options={},
        ),
        migrations.RemoveField(
            model_name="material",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descripcion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción del Proyecto"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="certificado_calidad_incluido",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="especificaciones_tecnicas",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="motivo_rechazo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="sku",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Código/SKU",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="stock_actual",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Stock Total (Suma de bodegas)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="certificado_calidad",
            field=models.FileField(
                blank=True,
                help_text="Certificado de calidad subido por bodega",
                null=True,
                upload_to="certificados/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INGRESO", "Ingreso por Compra (Abastecimiento)"),
                    ("SALIDA", "Salida por Requerimiento (Despacho)"),
                    ("AJUSTE", "Ajuste Manual de Inventario"),
                    ("VENTA", "Venta a Terceros"),
                    ("TRANSFERENCIA", "Transferencia entre Bodegas"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="documento_respaldo",
            field=models.FileField(
                blank=True,
                help_text="Factura o Certificado provisto por el proveedor",
                null=True,
                upload_to="compras_facturas/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador (Cotizando)"),
                    ("EMITIDA", "Emitida al Proveedor"),
                    ("RECIBIDA_PARCIAL", "Recibida Parcialmente (Alerta Compras)"),
                    ("RECIBIDA", "Recibida Total (Stock Actualizado)"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requerimiento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de Aprobación"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                    ("DESPACHADO", "Despachado"),
                    ("EN_COMPRAS", "Enviado a Compras"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudcompra",
            name="observaciones_admin",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="solicitudcompra",
            name="requerimiento_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.requerimiento",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="bodega_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_ingreso",
                to="web.bodega",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="bodega_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_salida",
                to="web.bodega",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="bodega_proyecto",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyecto_asociado",
                to="web.bodega",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.subcategoria",
            ),
        ),
        migrations.CreateModel(
            name="StockBodega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bodega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="web.bodega",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks_bodegas",
                        to="web.material",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "bodega")},
            },
        ),
    ]
