# Generated by Django 6.0.1 on 2026-09-15 12:49

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_detallerequerimiento_estado_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(help_text='Cédula o documento de identidad', max_length=20, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo / Anterior')], default='ACTIVO', max_length=10)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('motivo_salida', models.TextField(blank=True)),
                ('periodicidad_pago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal')], default='MENSUAL', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AlterField(
            model_name='historicalmovimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso por Compra (Abastecimiento)'), ('SALIDA', 'Salida por Requerimiento (Despacho)'), ('AJUSTE', 'Ajuste Manual de Inventario'), ('VENTA', 'Venta a Terceros'), ('TRANSFERENCIA', 'Transferencia entre Bodegas'), ('PRESTAMO', 'Préstamo a Trabajador'), ('DEVOLUCION_PRESTAMO', 'Devolución de Préstamo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso por Compra (Abastecimiento)'), ('SALIDA', 'Salida por Requerimiento (Despacho)'), ('AJUSTE', 'Ajuste Manual de Inventario'), ('VENTA', 'Venta a Terceros'), ('TRANSFERENCIA', 'Transferencia entre Bodegas'), ('PRESTAMO', 'Préstamo a Trabajador'), ('DEVOLUCION_PRESTAMO', 'Devolución de Préstamo')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionHorasExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_ordinaria', models.TimeField()),
                ('hora_fin_ordinaria', models.TimeField()),
                ('hora_inicio_extraordinaria', models.TimeField()),
                ('hora_fin_extraordinaria', models.TimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTrabajador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(db_index=True, help_text='Cédula o documento de identidad', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo / Anterior')], default='ACTIVO', max_length=10)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('motivo_salida', models.TextField(blank=True)),
                ('periodicidad_pago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal')], default='MENSUAL', max_length=10)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical trabajador',
                'verbose_name_plural': 'historical Trabajadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='web.trabajador')),
            ],
            options={
                'ordering': ['-periodo_fin'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PRESTADO', 'Prestado / Pendiente de Devolución'), ('DEVUELTO', 'Devuelto')], default='PRESTADO', max_length=10)),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_entregados', to='web.bodega')),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_entregados', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='web.material')),
                ('movimiento_salida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamo_origen', to='web.movimientoinventario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='web.trabajador')),
            ],
            options={
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('condicion', models.CharField(choices=[('BUEN_ESTADO', 'Buenas condiciones'), ('CON_OBSERVACIONES', 'Con observaciones / daños')], default='BUEN_ESTADO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('movimiento_ingreso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucion_prestamo', to='web.movimientoinventario')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='web.prestamoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='SalarioTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio_vigencia', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Vacío = salario vigente actual', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salarios_registrados', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='web.trabajador')),
            ],
            options={
                'ordering': ['-fecha_inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='web.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria')], max_length=15)),
                ('cantidad_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Pendiente hasta integrar la fórmula oficial de cálculo de horas extra.', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras_registradas', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extras_incluidas', to='web.pago')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='web.trabajador')),
            ],
            options={
                'verbose_name_plural': 'Horas Extra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrestamoHerramienta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PRESTADO', 'Prestado / Pendiente de Devolución'), ('DEVUELTO', 'Devuelto')], default='PRESTADO', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bodega_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.bodega')),
                ('entregado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.material')),
                ('movimiento_salida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.movimientoinventario')),
                ('trabajador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.trabajador')),
            ],
            options={
                'verbose_name': 'historical prestamo herramienta',
                'verbose_name_plural': 'historical prestamo herramientas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.trabajador')),
            ],
            options={
                'verbose_name': 'historical pago',
                'verbose_name_plural': 'historical pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EntregaDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativo', models.TextField()),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_directa', to='web.movimientoinventario')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.proyecto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_directas', to='web.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_incluidos', to='web.pago')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='web.trabajador')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('trabajador', 'periodo_inicio', 'periodo_fin'), name='unico_pago_por_periodo'),
        ),
    ]
