# Generated by Django 6.0.1 on 2026-09-15 15:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_trabajador_alter_historicalmovimientoinventario_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='tipo',
            field=models.CharField(choices=[('DESCUENTO', 'Descuento (multa, atraso, etc.)'), ('ANTICIPO', 'Anticipo (adelanto de dinero)')], default='DESCUENTO', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='aporte_iess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='bonificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='dias_laborados',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='total_anticipos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='aporte_iess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='bonificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='dias_laborados',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pago',
            name='total_anticipos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PeriodoNominaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1 = Enero ... 12 = Diciembre')),
                ('bonificacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aporte_iess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_nomina_registrados', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_mensuales', to='web.trabajador')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='periodo_mensual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.periodonominamensual'),
        ),
        migrations.AddField(
            model_name='pago',
            name='periodo_mensual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='web.periodonominamensual'),
        ),
        migrations.AddConstraint(
            model_name='periodonominamensual',
            constraint=models.UniqueConstraint(fields=('trabajador', 'anio', 'mes'), name='unico_periodo_mensual_por_trabajador'),
        ),
    ]
