# Generated by Django 6.0.2 on 2026-05-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_bodega_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='estado_aprobacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado para Compra'), ('COMPRADO', 'Órden de Compra Generada'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15),
        ),
    ]
