# Generated by Django 6.0.1 on 2026-09-15 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_descuento_tipo_historicalpago_aporte_iess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariotrabajador',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horariotrabajador',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='fecha_pago_confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='pagado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='total_horas_normales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='banco',
            field=models.CharField(blank=True, choices=[('PICHINCHA', 'Banco Pichincha'), ('GUAYAQUIL', 'Banco Guayaquil'), ('PACIFICO', 'Banco del Pacífico'), ('PRODUBANCO', 'Produbanco'), ('INTERNACIONAL', 'Banco Internacional')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Correo del trabajador; se usa para notificarle cuando se le realiza un pago.', max_length=254),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='generado_automaticamente',
            field=models.BooleanField(default=False, help_text='Calculado desde el detalle de días de un pago, no ingresado a mano.'),
        ),
        migrations.AddField(
            model_name='pago',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago_confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='total_horas_normales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='banco',
            field=models.CharField(blank=True, choices=[('PICHINCHA', 'Banco Pichincha'), ('GUAYAQUIL', 'Banco Guayaquil'), ('PACIFICO', 'Banco del Pacífico'), ('PRODUBANCO', 'Produbanco'), ('INTERNACIONAL', 'Banco Internacional')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Correo del trabajador; se usa para notificarle cuando se le realiza un pago.', max_length=254),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='HorarioTrabajadorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('trabaja', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='web.horariotrabajador')),
            ],
            options={
                'ordering': ['dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('horario', 'dia_semana'), name='unico_dia_por_horario')],
            },
        ),
    ]
