# Generated by Django 6.0.2 on 2026-05-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_cotizacionitem_estado_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='estado_item',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO_BODEGA', 'Aprobado para Despacho en Bodega'), ('EN_COMPRAS', 'Mandar a Compras (Falta Stock)'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='detallerequerimiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones'),
        ),
    ]
