# Generated by Django 6.0.1 on 2026-09-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_horariotrabajador_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodonominamensual',
            name='aporte_iess',
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='aporte_iess_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fijo mensual del aporte IESS de este trabajador (no varía mes a mes salvo que se actualice aquí).', max_digits=10),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='aporte_iess_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fijo mensual del aporte IESS de este trabajador (no varía mes a mes salvo que se actualice aquí).', max_digits=10),
        ),
    ]
