# Generated by Django 6.0.1 on 2026-09-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_periodonominamensual_aporte_iess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpago',
            name='datos_formulario',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot de los datos del formulario mientras el pago está en BORRADOR, para poder reanudar la edición.'),
        ),
        migrations.AddField(
            model_name='pago',
            name='datos_formulario',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot de los datos del formulario mientras el pago está en BORRADOR, para poder reanudar la edición.'),
        ),
        migrations.AlterField(
            model_name='historicalpago',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10),
        ),
    ]
